### ISSUE TITLE
Documentation correction: doc/OPENSSL.README

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [bammv/sguil#13]
Steps for SSL Certificate creation described in (https://github.com/bammv/sguil/blob/master/doc/OPENSSL.README) need to be corrected as below:

No correction for these steps:
1. openssl req -out CA.pem -new -x509
2. openssl genrsa -out sguild.key 1024
3. openssl req -key sguild.key -new -out sguild.req

Correction for last two:
4. echo 01 > CA.srl
5. openssl x509 -req -in sguild.req -CA CA.pem -CAkey privkey.pem -out sguild.pem

* Without existing CA.srl (or file.srl), step 5 will fail.
* The "-CAserial file.sr1" code section is not needed in step 5, because OpenSSL uses CA.srl for serial by default. Just make sure it has been created before running step 5.

**Comment by bammv** [comment]
Fix committed.
